# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
email:
description: > # this means to ignore newlines until "baseurl:"

# deploy urls
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mcguia.github.io/rfa-blueprint-2020"
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://2018state.results4america.org" # the base hostname & protocol for your site, e.g. http://example.com
project_url: "/state-standard-of-excellence/"

# dev urls
# baseurl: "/rfa-2019" # the subpath of your site, e.g. /blog
# url: "https://objectively.github.io"
# # baseurl: "" # the subpath of your site, e.g. /blog
# # url: "https://2018state.results4america.org" # the base hostname & protocol for your site, e.g. http://example.com
# project_url: "/rfa-2019/"
twitter_username: results4america
github_username:
seo_image_path: '/images/rfa-og.jpg'
content_year: 2020

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json

timezone: America/New_York

# Folder Structure
source: ./source
# sass_dir: source/css


contentful:
  spaces:
    - action: # Jekyll _data folder identifier - Required
        space: ENV_RFA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_RFA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: action
    - example: # Jekyll _data folder identifier - Required
        space: ENV_RFA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_RFA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: example
    - indexPage: # Jekyll _data folder identifier - Required
        space: ENV_RFA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_RFA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: indexPage
    - strategy: # Jekyll _data folder identifier - Required
        space: ENV_RFA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_RFA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: strategy
    - theme: # Jekyll _data folder identifier - Required
        space: ENV_RFA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_RFA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: theme
          


page_gen:
  - data: contentful.theme.theme
    template: theme
    name: title
    dir: theme
    filter_condition: "record['year'] == '2020'"